# CentOS 7 (glibc 2.17) + GCC 15 toolchain for building Node.js >= 22.3 binaries
# that run on glibc 2.17.
# Copied from nodejs/unofficial-builds recipes/centos7-toolchain (MIT, commit c41adbe,
# 2026-09-03) with the Rust step dropped (Rust is only needed for the Temporal API
# in Node 26+). files/ is that recipe's files/ directory, unchanged; source tarballs
# are SHA-256 checked via files/checksums.sh.
FROM --platform=linux/amd64 centos:7

ARG GID=1000
ARG UID=1000

RUN groupadd --gid $GID node \
    && adduser --gid $GID --uid $UID node

COPY --chmod=755  files/installPrerequisites  /root/installPrerequisites
COPY              files/*.repo                /etc/yum.repos.d/
RUN /root/installPrerequisites

COPY  --chmod=755  files/installFromSourceCode  /root/installFromSourceCode
COPY  --chmod=755  files/opt__gcc15__enable     /opt/gcc15/enable
COPY  --chmod=755  files/checksums.sh           /root/checksums.sh

RUN   --mount=type=cache,target=/root/.ccache  . /root/checksums.sh  &&  /root/installFromSourceCode  https://www.python.org/ftp/python/3.13.5/Python-3.13.5.tar.xz      "$sha256_python313" '--prefix=/usr/local/'
RUN   --mount=type=cache,target=/root/.ccache  . /root/checksums.sh  &&  /root/installFromSourceCode  https://gcc.gnu.org/pub/gcc/releases/gcc-15.1.0/gcc-15.1.0.tar.xz  "$sha256_gcc15"     '--prefix=/opt/gcc15/  --with-default-libstdcxx-abi=gcc4-compatible  --enable-languages=c,c++  --enable-checking=release  --enable-gnu-indirect-function  --with-linker-hash-style=gnu  --disable-bootstrap  --disable-multilib  --build=x86_64-redhat-linux'
