#!/usr/bin/env bash
# Smoke-tests a Node.js base as a single executable application (SEA):
# embeds a tiny script with postject, runs it, and checks argv and NODE_OPTIONS handling.
#   perf/sea-smoke.sh <base-node-binary> <official-node-of-the-same-version>
# The SEA blob must be generated by the same Node.js version as the base.
set -euo pipefail
BASE=$1
GEN=$2
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

ext=""; case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) ext=".exe";; esac
[ "$("$BASE" -v)" = "$("$GEN" -v)" ] || { echo "base $("$BASE" -v) != generator $("$GEN" -v)" >&2; exit 1; }

cat > "$work/app.js" <<'JS'
const sea = require('node:sea');
const out = { isSea: sea.isSea(), argv: process.argv.slice(1), execArgv: process.execArgv };
console.log(JSON.stringify(out));
JS
cat > "$work/sea-config.json" <<'JSON'
{ "main": "app.js", "output": "app.blob", "disableExperimentalSEAWarning": true,
  "useCodeCache": false, "useSnapshot": false, "execArgv": [], "execArgvExtension": "none" }
JSON
(cd "$work" && "$GEN" --experimental-sea-config sea-config.json)

cp "$BASE" "$work/app$ext"
macho=()
if [ "$(uname -s)" = "Darwin" ]; then
  codesign --remove-signature "$work/app$ext"
  macho=(--macho-segment-name NODE_SEA)
fi
npx -y postject@1.0.0-alpha.6 "$work/app$ext" NODE_SEA_BLOB "$work/app.blob" \
  --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 "${macho[@]}"
# macOS refuses to run a binary whose signature was invalidated by the injection.
[ "$(uname -s)" = "Darwin" ] && codesign --sign - "$work/app$ext"

echo 'require("fs").writeFileSync(process.argv0 + ".honoured", "x")' > "$work/inject.js"
out=$(NODE_OPTIONS="--require $work/inject.js" "$work/app$ext" one two)
echo "SEA output: $out"
echo "$out" | grep -q '"isSea":true' || { echo "not running as SEA" >&2; exit 1; }
echo "$out" | grep -q '"one","two"' || { echo "user args not passed through" >&2; exit 1; }
echo "$out" | grep -q '"execArgv":\[\]' || { echo "unexpected execArgv" >&2; exit 1; }
if ls "$work"/*.honoured >/dev/null 2>&1; then echo "NODE_OPTIONS was honoured" >&2; exit 1; fi
echo "SEA smoke test passed"
